# Generated by Django 2.2.6 on 2019-11-04 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=800)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('summary', models.TextField()),
                ('title', models.CharField(max_length=280)),
                ('feeds', models.ManyToManyField(related_name='entries', to='feeds.Feed')),
            ],
        ),
    ]
