# Generated by Django 2.2.6 on 2019-12-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_entry_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='link',
            field=models.URLField(max_length=800, unique=True),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['link'], name='feeds_entry_link_64221a_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['published'], name='feeds_entry_publish_1bfd6f_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['timestamp'], name='feeds_entry_timesta_fb54eb_idx'),
        ),
    ]
