# Generated by Django 2.2.6 on 2019-12-11 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_auto_20191204_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-published']},
        ),
    ]
