# Generated by Django 2.2.6 on 2019-12-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_auto_20191211_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ['link']},
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['link'], name='feeds_feed_link_7cbe82_idx'),
        ),
    ]
