# Generated by Django 2.2.6 on 2019-12-14 04:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0006_auto_20191214_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
